[project]
name = "Wizzer"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "K-Grachev-2106756", email = "m2106756@edu.misis.ru"},
]
dependencies = ["fastapi>=0.115.6", "uvicorn>=0.32.1", "elasticsearch>=8.16.0", "pandas>=2.2.3", "numpy>=2.0.2", "requests>=2.32.3", "pydantic>=2.10.3"]
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[dependency-groups]
dev = [
    "transformers>=4.46.3",
    "datasets>=3.1.0",
    "torch>=2.5.1",
    "scikit-learn>=1.5.2",
    "undetected-chromedriver>=3.5.5",
    "bs4>=0.0.2",
]
